name: app_environment
channels:
  - snowflake
dependencies:
  - certifi=*
  - cryptography=*
  - gravis=*
  - matplotlib=*
  - networkx=*
  - numpy=*
  - pandas=*
  - pydantic=*
  - pydantic-core
  - pydot=*
  - python-dotenv=*
  - python-graphviz=*
  - sqlalchemy=*
  - tabulate=*
