-- NOTE: run this script after you log into the account

USE ROLE ACCOUNTADMIN;

CREATE USER TOKENFLOW_ADMIN
    PASSWORD='<PASSWORD_HERE>'
    DEFAULT_ROLE = SYSADMIN
    DEFAULT_SECONDARY_ROLES = ('ALL')
    MUST_CHANGE_PASSWORD = FALSE
    LOGIN_NAME = TOKENFLOW_ADMIN
    DISPLAY_NAME = TOKENFLOW_ADMIN
    FIRST_NAME = TOKENFLOW_ADMIN
    LAST_NAME = TOKENFLOW_ADMIN
    ;

CREATE USER TOKENFLOW_DEV_GNN
    PASSWORD='<PASSWORD_HERE>'
    DEFAULT_ROLE = SYSADMIN
    DEFAULT_SECONDARY_ROLES = ('ALL')
    MUST_CHANGE_PASSWORD = FALSE
    LOGIN_NAME = TOKENFLOW_DEV_GNN
    DISPLAY_NAME = TOKENFLOW_DEV_GNN
    FIRST_NAME = TOKENFLOW_DEV_GNN
    LAST_NAME = TOKENFLOW_DEV_GNN
    ;

CREATE USER TOKENFLOW_DEV_GRAG
    PASSWORD='<PASSWORD_HERE>'
    DEFAULT_ROLE = SYSADMIN
    DEFAULT_SECONDARY_ROLES = ('ALL')
    MUST_CHANGE_PASSWORD = FALSE
    LOGIN_NAME = TOKENFLOW_DEV_GRAG
    DISPLAY_NAME = TOKENFLOW_DEV_GRAG
    FIRST_NAME = TOKENFLOW_DEV_GRAG
    LAST_NAME = TOKENFLOW_DEV_GRAG
    ;

CREATE USER TOKENFLOW_DEV_EGO
    PASSWORD='<PASSWORD_HERE>'
    DEFAULT_ROLE = SYSADMIN
    DEFAULT_SECONDARY_ROLES = ('ALL')
    MUST_CHANGE_PASSWORD = FALSE
    LOGIN_NAME = TOKENFLOW_DEV_EGO
    DISPLAY_NAME = TOKENFLOW_DEV_EGO
    FIRST_NAME = TOKENFLOW_DEV_EGO
    LAST_NAME = TOKENFLOW_DEV_EGO
    ;

CREATE USER TOKENFLOW_DEV_KG
    PASSWORD='<PASSWORD_HERE>'
    DEFAULT_ROLE = SYSADMIN
    DEFAULT_SECONDARY_ROLES = ('ALL')
    MUST_CHANGE_PASSWORD = FALSE
    LOGIN_NAME = TOKENFLOW_DEV_KG
    DISPLAY_NAME = TOKENFLOW_DEV_KG
    FIRST_NAME = TOKENFLOW_DEV_KG
    LAST_NAME = TOKENFLOW_DEV_KG
    ;

-- grant roles
GRANT ROLE ACCOUNTADMIN, SYSADMIN TO USER TOKENFLOW_ADMIN;
GRANT ROLE ACCOUNTADMIN, SYSADMIN TO USER TOKENFLOW_DEV_GNN;
GRANT ROLE ACCOUNTADMIN, SYSADMIN TO USER TOKENFLOW_DEV_GRAG;
GRANT ROLE ACCOUNTADMIN, SYSADMIN TO USER TOKENFLOW_DEV_EGO;
GRANT ROLE ACCOUNTADMIN, SYSADMIN TO USER TOKENFLOW_DEV_KG;

-- set default role to sysadmin
ALTER USER TOKENFLOW_ADMIN SET DEFAULT_ROLE=SYSADMIN;
ALTER USER TOKENFLOW_DEV_GNN SET DEFAULT_ROLE=SYSADMIN;
ALTER USER TOKENFLOW_DEV_GRAG SET DEFAULT_ROLE=SYSADMIN;
ALTER USER TOKENFLOW_DEV_EGO SET DEFAULT_ROLE=SYSADMIN;
ALTER USER TOKENFLOW_DEV_KG SET DEFAULT_ROLE=SYSADMIN;
