--
-- data
--
USE ROLE ACCOUNTADMIN;
USE DATABASE TF_DB;
USE SCHEMA TF_SCHEMA;


-- token-transfers.csv
CREATE OR REPLACE TABLE TOKEN_TRANSFERS (
    LAUNCHPAD VARCHAR,
    TOKEN VARCHAR,
    SYMBOL VARCHAR,
    NAME VARCHAR,
    BLOCK_NUMBER NUMBER,
    BLOCK_TIMESTAMP DATETIME,
    TX_HASH VARCHAR,
    FROM_ADDRESS VARCHAR,
    L1_FEE NUMBER,
    L2_FEE NUMBER,
    SENDER VARCHAR,
    RECEIVER VARCHAR,
    AMOUNT NUMBER
);

ALTER TABLE TF_DB.TF_SCHEMA.TOKEN_TRANSFERS SET CHANGE_TRACKING = TRUE;

COPY INTO TOKEN_TRANSFERS
    from '@"TF_DB"."TF_SCHEMA"."TF_STAGE"/token-transfers.csv'
    FILE_FORMAT = (
        TYPE = CSV
        --COMPRESSION = BZ2
        SKIP_HEADER = 1
        NULL_IF = '\\N'
        EMPTY_FIELD_AS_NULL = TRUE
        DATE_FORMAT = AUTO --'YYYY-MM-DD HH:MM:SS'
        FIELD_OPTIONALLY_ENCLOSED_BY = '"'
        ESCAPE = '\\'
    )
    ON_ERROR = CONTINUE
;



-- virtuals-agents.csv
CREATE OR REPLACE TABLE VIRTUALS_AGENTS (
    AGENT_TOKEN_ADDRESS VARCHAR,
    NAME VARCHAR,
    SYMBOL VARCHAR,
    DESCRIPTION VARCHAR,
    CREATED_AT DATETIME,
    LP VARCHAR,
    TBA VARCHAR,
    WALLETS VARCHAR,
    IS_PUBLIC BOOLEAN,
    IS_PREMIUM BOOLEAN,
    X_USERNAME VARCHAR,
    STATUS VARCHAR,
    EXTRA_DATA VARCHAR,
    ADDED_AT DATETIME
);

ALTER TABLE TF_DB.TF_SCHEMA.VIRTUALS_AGENTS SET CHANGE_TRACKING = TRUE;

COPY INTO VIRTUALS_AGENTS
    from '@"TF_DB"."TF_SCHEMA"."TF_STAGE"/virtuals-agents.csv'
    FILE_FORMAT = (
        TYPE = CSV
        SKIP_HEADER = 1
        NULL_IF = '\\N'
        EMPTY_FIELD_AS_NULL = TRUE
        DATE_FORMAT = AUTO --'YYYY-MM-DD HH:MM:SS'
        FIELD_OPTIONALLY_ENCLOSED_BY = '"'
        ESCAPE = '\\'
    )
    ON_ERROR = CONTINUE
;



-- token-snapshot.csv
CREATE TABLE TOKEN_SNAPSHOT (
    NAME VARCHAR,
    TOKEN_ADDRESS VARCHAR,
    SNAPSHOT_TIME DATETIME,
    TRANSFER_COUNT NUMBER,
    TRANSFER_AMOUNT NUMBER,
    BUY_COUNT NUMBER,
    BUY_AMOUNT NUMBER,
    SELL_COUNT NUMBER,
    SELL_AMOUNT NUMBER,
    MINT_COUNT NUMBER,
    MINT_AMOUNT NUMBER,
    BURN_COUNT NUMBER,
    BURN_AMOUNT NUMBER,
    TOTAL_SUPPLY NUMBER,
    HOLDER_COUNT NUMBER,
    USD_PRICE NUMBER,
    TVL NUMBER
);

ALTER TABLE TF_DB.TF_SCHEMA.TOKEN_SNAPSHOT SET CHANGE_TRACKING = TRUE;

COPY INTO TOKEN_SNAPSHOT
    from '@"TF_DB"."TF_SCHEMA"."TF_STAGE"/token-snapshot.csv'
    FILE_FORMAT = (
        TYPE = CSV
        SKIP_HEADER = 1
        NULL_IF = '\\N'
        EMPTY_FIELD_AS_NULL = TRUE
        DATE_FORMAT = AUTO --'YYYY-MM-DD HH:MM:SS'
        FIELD_OPTIONALLY_ENCLOSED_BY = '"'
        ESCAPE = '\\'
    )
    ON_ERROR = CONTINUE
;




-- running-token-balances.csv
CREATE TABLE RUNNING_TOKEN_BALANCES (
    TOKEN_ADDRESS VARCHAR,
    HOLDER VARCHAR,
    BALANCE_CHANGE_TIME DATETIME,
    RUNNING_BALANCE NUMBER
);

ALTER TABLE TF_DB.TF_SCHEMA.RUNNING_TOKEN_BALANCES SET CHANGE_TRACKING = TRUE;

COPY INTO RUNNING_TOKEN_BALANCES
    from '@"TF_DB"."TF_SCHEMA"."TF_STAGE"/running-token-balances.csv'
    FILE_FORMAT = (
        TYPE = CSV
        SKIP_HEADER = 1
        NULL_IF = '\\N'
        EMPTY_FIELD_AS_NULL = TRUE
        DATE_FORMAT = AUTO --'YYYY-MM-DD HH:MM:SS'
        FIELD_OPTIONALLY_ENCLOSED_BY = '"'
        ESCAPE = '\\'
    )
    ON_ERROR = CONTINUE
;